services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./env/.env
    depends_on:
      - mongo
    command: npm run start

  mongo:
    image: mongo

  redis:
    image: redis
