services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: test
    ports:
      - "3000:3000"
    env_file:
      - ./env/test/.node-app_test
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    command: npm run test

  mongo:
    image: mongo
    env_file:
      - ./env/test/.mongo_test
    volumes:
      - mongo-db-test:/data/db

volumes:
  mongo-db-test:
    driver: local
  