version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file:
      - ./env/.node-app_dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
  mongo:
    env_file:
      - ./env/.mongo_dev
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
